#!/usr/bin/env python3
"""Generate musl codepages.h entries for the z/OS XMLSS EBCDIC set.

Usage: gen_codepages.py <musl-src-dir> <entries-out> <probe-consts-out>

Reads reference mappings through verify.py (authority = glibc with the
documented overrides, cross-checked against ICU/Python there), validates the
musl packing model against the in-tree ibm1047 entry, then emits:

  <entries-out>       codepages.h text for every page not already in musl
  <probe-consts-out>  C table of {alias, FNV-1a-64 golden} for run-caps

Every generated table is round-tripped through a reimplementation of musl's
legacy_map() before being written."""
import re
import sys

from verify import PAGES, authority_map, fnv64, golden


def read_c_string_bytes(path):
    text = re.sub(r"/\*.*?\*/", "", open(path).read(), flags=re.S)
    out = bytearray()
    for lit in re.findall(r'"((?:[^"\\]|\\.)*)"', text):
        i = 0
        while i < len(lit):
            if lit[i] == "\\":
                m = re.match(r"\\([0-7]{1,3})", lit[i:])
                assert m, f"unsupported escape {lit[i:i+4]!r}"
                out.append(int(m.group(1), 8))
                i += len(m.group(0))
            else:
                out.append(ord(lit[i]))
                i += 1
    return bytes(out)


def parse_charmaps(blob):
    maps, i = [], 0
    while i < len(blob):
        aliases = []
        while blob[i]:
            j = blob.index(0, i)
            aliases.append(blob[i:j].decode())
            i = j + 1
        i += 1
        elided = blob[i]
        i += 1
        assert elided <= 64, f"unexpected type byte {elided:#o}"
        n = (64 - elided) * 5
        maps.append((aliases, elided, blob[i:i + n]))
        i += n
    return maps


def legacy_map(elided, table, legacy_chars, c):
    if c < 4 * elided:
        return c
    x = c - 4 * elided
    v = (table[x * 5 // 4] >> (2 * x % 8)
         | table[x * 5 // 4 + 1] << (8 - 2 * x % 8)) & 1023
    return v if v < 256 else legacy_chars[v - 256]


def pack_entry(aliases, mapping, legacy_chars):
    elided = 0
    while elided < 64 and all(mapping[4 * elided + k] == 4 * elided + k
                              for k in range(4)):
        elided += 1
    vals = []
    for c in range(4 * elided, 256):
        cp = mapping[c]
        if cp < 256:
            vals.append(cp)
        else:
            assert cp in legacy_chars, f"U+{cp:04X} missing from legacy_chars"
            vals.append(256 + legacy_chars.index(cp))
    table = bytearray()
    for q in range(0, len(vals), 4):
        e0, e1, e2, e3 = vals[q:q + 4]
        table += bytes([e0 & 255,
                        (e0 >> 8) | ((e1 & 0x3F) << 2),
                        (e1 >> 6) | ((e2 & 0x0F) << 4),
                        (e2 >> 4) | ((e3 & 0x03) << 6),
                        e3 >> 2])
    for c in range(256):
        got = legacy_map(elided, bytes(table), legacy_chars, c)
        assert got == mapping[c], f"pack/unpack mismatch at byte {c:#04x}"
    lines = [""]
    lines += [f'"{a}\\0"' for a in aliases]
    lines.append(f'"\\0\\{elided:o}"')
    for i in range(0, len(table), 20):
        lines.append('"' + "".join(f"\\{b:o}" for b in table[i:i + 20]) + '"')
    return "\n".join(lines) + "\n", elided, len(table)


def main():
    musl, entries_out, consts_out = sys.argv[1:4]
    legacy_chars = [int(x, 0) for x in
                    re.findall(r"0x[0-9a-fA-F]+|\d+",
                               open(f"{musl}/src/locale/legacychars.h").read())]

    # Validate the packing model + authority against musl's in-tree ibm1047.
    blob = read_c_string_bytes(f"{musl}/src/locale/codepages.h")
    intree = {a: m for m in parse_charmaps(blob) for a in m[0]}
    p1047 = next(p for p in PAGES if p[5])
    m = intree[p1047[4][0]]
    decoded = [legacy_map(m[1], m[2], legacy_chars, c) for c in range(256)]
    assert decoded == authority_map(p1047), "in-tree ibm1047 != authority"
    print(f"OK: in-tree ibm1047 matches authority (format model validated)")

    entries, consts, total = [], [], 0
    for page in PAGES:
        name, _g, _i, _py, aliases, in_tree = page
        auth = authority_map(page)
        g = golden(page)
        consts.append((aliases[0], g))
        if in_tree:
            continue
        entry, elided, tbytes = pack_entry(aliases, auth, legacy_chars)
        size = sum(len(a) + 1 for a in aliases) + 2 + tbytes
        total += size
        entries.append(entry)
        print(f"OK: {name}: elided={elided} table={tbytes}B entry={size}B "
              f"golden=0x{g:016x}")

    with open(entries_out, "w") as f:
        f.write("".join(entries))
    with open(consts_out, "w") as f:
        f.write("/* generated by tools/ebcdic/gen_codepages.py -- FNV-1a 64\n"
                "   of the UTF-32LE decode of bytes 0..255 per codepage */\n")
        for alias, g in consts:
            f.write(f'\t{{ "{alias}", 0x{g:016x}ULL }},\n')
    print(f"{len(entries)} entries, {total} bytes added to charmaps[]; "
          f"{len(consts)} probe constants")


if __name__ == "__main__":
    main()
